name: Trigger auto deployment for container-app-42mhgddlhksdg

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-42mhgddlhksdg-AutoDeployTrigger-9b8b4f7f-372d-4c49-aacc-500e07b4f8b1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP42MHGDDLHKSDG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP42MHGDDLHKSDG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP42MHGDDLHKSDG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP42MHGDDLHKSDG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP42MHGDDLHKSDG_REGISTRY_PASSWORD }}
          containerAppName: container-app-42mhgddlhksdg
          resourceGroup: appspacesragapp9fa29b5e
          imageToBuild: default/container-app-42mhgddlhksdg:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


